GET http://localhost:5000/books
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5NTE5NjA5MCwiZXhwIjoxNjk1MTk2MzkwfQ.-YMyWo0XQk0tm-lNkL-OhaF36Cw08UbrPk9ZLsBKfsc

###

POST http://localhost:5500/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###
POST http://localhost:5500/auth/refreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGV0ZXgiLCJpYXQiOjE2MjA0NzQxODV9.I8lKqN5PLE3Vz103O5Ml7ePJWsUksJoeA81uYFeCc6o"
}

###
POST http://localhost:5500/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGV0ZXgiLCJpYXQiOjE2MjA0NzQxODV9.I8lKqN5PLE3Vz103O5Ml7ePJWsUksJoeA81uYFeCc6o"
}